os: linux
language: cpp
services:
  - docker
before_install:
  - docker pull debian:10-slim
  - docker run -it -d --name build debian:10-slim bash
  - docker exec build apt update
  # install deps
  - docker exec build apt install build-essential devscripts lintian dh-make git wget jq python3 python3-dev python3-pip unzip cmake sudo -y
  - docker exec build pip3 install pyangbind
  - docker exec build bash -c "cd /root/ && git clone https://github.com/atolab/zenoh-c -b 0.3.0 --depth 1 && cd zenoh-c && make && make install"
  - docker exec build bash -c "cd /root/ && git clone https://github.com/atolab/zenoh-python -b 0.3.0 --depth 1 && cd zenoh-python && python3 setup.py install"
  - docker exec build bash -c "cd /root/ && git clone https://github.com/atolab/yaks-python -b 0.3.0 --depth 1 && cd yaks-python && make install"
  - docker exec build bash -c "cd /root/ && git clone https://github.com/eclipse-fog05/sdk-python -b 0.2.x --depth 1 && cd sdk-python && make && make install"
  - docker exec build bash -c "cd /root/ && git clone https://github.com/eclipse-fog05/api-python -b 0.2.x --depth 1 && cd api-python && make install"
  # copying repo inside container
  - docker cp ../plugin-fdu-ros2 build:/root/
script:
  - docker exec build bash -c "mkdir /root/build && cd /root && cp -r plugin-fdu-ros2 build/fog05-plugin-fdu-ros2-0.2.1 && cd build/fog05-plugin-fdu-ros2-0.2.1 && rm -rf .git && make clean && cd .. && tar -czvf fog05-plugin-fdu-ros2-0.2.1.tar.gz fog05-plugin-fdu-ros2-0.2.1"
  - docker exec build bash -c "export DEBEMAIL=\"info@adlink-labs.tech\" && export DEBFULLNAME=\"ATO Labs\" && cd /root/build/fog05-plugin-fdu-ros2-0.2.1 && dh_make -f ../fog05-plugin-fdu-ros2-0.2.1.tar.gz -s -y"
  - docker exec build bash -c 'cd /root/build/fog05-plugin-fdu-ros2-0.2.1 && printf "override_dh_auto_install:\n\tmkdir -p \$\$(pwd)/debian/fog05-plugin-fdu-native/usr/bin/\n\tmkdir -p \$\$(pwd)/debian/fog05-plugin-fdu-ros2/lib/systemd/system/\n\t\$(MAKE) ros2_PLUGIN_DIR=\$\$(pwd)/debian/fog05-plugin-fdu-ros2/etc/fos/plugins/plugin-fdu-ros2 SYSTEMD_DIR=\$\$(pwd)/debian/fog05-plugin-fdu-ros2/lib/systemd/system/ BIN_DIR=\$\$(pwd)/debian/fog05-plugin-fdu-native/usr/bin install">> debian/rules'
  - docker exec build bash -c "cd /root/build/fog05-plugin-fdu-ros2-0.2.1 && debuild --preserve-envvar PATH -us -uc  && ls -l"
  - docker exec build bash -c "cd /root/build/ && dpkg -I fog05-plugin-fdu-ros2_0.2.1-1_amd64.deb"