language: rust
rust:
  # - stable
  # - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo check
  - cargo fmt -- --check
  - cargo build --release --all-targets --verbose
  - cargo deb --no-build --verbose
  - dpkg -I ./target/debian/fog05-hypervisor-ros2_0.3.0~alpha1_amd64.deb
